-- Ejecutar solo si DBUP_ALLOWED_CLIENTS ya existe sin la columna OS_USER.
-- En una instalacion nueva, este cambio ya esta incluido en 002_create_dbup_control_tables.sql.

ALTER TABLE DBUP_ALLOWED_CLIENTS
  ADD OS_USER VARCHAR2(128);

ALTER TABLE DBUP_ALLOWED_CLIENTS
  ADD HOST_NAME VARCHAR2(255);

ALTER TABLE DBUP_ALLOWED_CLIENTS
  ADD CLIENT_PROGRAM_NAME VARCHAR2(128) DEFAULT '*' NOT NULL;

UPDATE DBUP_ALLOWED_CLIENTS
   SET OS_USER = 'appuser'
 WHERE OS_USER IS NULL;

ALTER TABLE DBUP_ALLOWED_CLIENTS
  MODIFY OS_USER NOT NULL;

ALTER TABLE DBUP_ALLOWED_CLIENTS
  DROP CONSTRAINT UX_DBUP_ALLOWED_CLIENT;

ALTER TABLE DBUP_ALLOWED_CLIENTS
  ADD CONSTRAINT UX_DBUP_ALLOWED_CLIENT UNIQUE (ENVIRONMENT, IP_ADDRESS, OS_USER, HOST_NAME, CLIENT_PROGRAM_NAME);

COMMIT;
