-- JIRA_TICKET: DBUP-9999
-- TARGET_ENTITIES: 700,702
-- TARGET_SCHEMA: {{ENTIDAD}}

CREATE OR REPLACE FUNCTION {{ENTIDAD}}.FN_DBUP_TARGET_ENTITIES_TEST (
  p_value IN VARCHAR2
) RETURN VARCHAR2
IS
BEGIN
  RETURN 'DBUP_TARGET_ENTITIES_OK:{{ENTITY}}:' || p_value;
END;
/
