-- Ejecutar con un usuario DBA después de definir DBUP_USER, DBUP_ROLE,
-- DBUP_PASSWORD, DBUP_DEFAULT_TABLESPACE y DBUP_TEMP_TABLESPACE. El orquestador
-- 000_deploy_base_de_datos.sql los solicita de manera interactiva.

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM DBA_USERS
   WHERE USERNAME = '&&DBUP_USER';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE USER &&DBUP_USER IDENTIFIED BY "&&DBUP_PASSWORD"
        DEFAULT TABLESPACE &&DBUP_DEFAULT_TABLESPACE
        TEMPORARY TABLESPACE &&DBUP_TEMP_TABLESPACE
        ACCOUNT UNLOCK';
  ELSE
    EXECUTE IMMEDIATE 'ALTER USER &&DBUP_USER ACCOUNT UNLOCK';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM DBA_ROLES
   WHERE ROLE = '&&DBUP_ROLE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE ROLE &&DBUP_ROLE';
  END IF;
END;
/

GRANT CREATE SESSION TO &&DBUP_USER;

BEGIN
  EXECUTE IMMEDIATE 'GRANT &&DBUP_ROLE TO &&DBUP_USER';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-1031, -1919, -1924) THEN
      DBMS_OUTPUT.PUT_LINE('WARN: no se pudo otorgar &&DBUP_ROLE a &&DBUP_USER: ' || SQLERRM);
      DBMS_OUTPUT.PUT_LINE('WARN: se continuara con grants directos al usuario tecnico.');
    ELSE
      RAISE;
    END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM DBA_ROLE_PRIVS
   WHERE GRANTEE = '&&DBUP_USER'
     AND GRANTED_ROLE = '&&DBUP_ROLE';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER USER &&DBUP_USER DEFAULT ROLE &&DBUP_ROLE';
  ELSE
    DBMS_OUTPUT.PUT_LINE('WARN: &&DBUP_ROLE no quedo otorgado; se omite DEFAULT ROLE.');
  END IF;
END;
/
