-- JIRA_TICKET: DBUP-0002
-- TARGET_SCHEMA: ENTIDAD700

CREATE TABLE ENTIDAD700.DBUP_TEST_SHARED (
  TEST_ID      NUMBER NOT NULL,
  TEST_VALUE   VARCHAR2(100) NOT NULL,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY   VARCHAR2(128) DEFAULT SYS_CONTEXT('USERENV', 'SESSION_USER') NOT NULL,
  CONSTRAINT PK_DBUP_TEST_SHARED PRIMARY KEY (TEST_ID)
);

CREATE SEQUENCE ENTIDAD700.DBUP_TEST_SHARED_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE OR REPLACE FUNCTION ENTIDAD700.FN_DBUP_TEST_SHARED (
  p_value IN VARCHAR2
) RETURN VARCHAR2
IS
BEGIN
  RETURN 'DBUP_SHARED_OK:' || p_value;
END;
/

CREATE OR REPLACE TRIGGER ENTIDAD700.TRG_DBUP_TEST_SHARED_BI
BEFORE INSERT ON ENTIDAD700.DBUP_TEST_SHARED
FOR EACH ROW
BEGIN
  IF :NEW.TEST_ID IS NULL THEN
    :NEW.TEST_ID := ENTIDAD700.DBUP_TEST_SHARED_SEQ.NEXTVAL;
  END IF;
END;
/

INSERT INTO ENTIDAD700.DBUP_TEST_SHARED (TEST_ID, TEST_VALUE)
VALUES (NULL, ENTIDAD700.FN_DBUP_TEST_SHARED('PROMOTION_TEST'));

COMMIT;
